import logging
from pathlib import Path
from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine

from app.models.base import Base
import app.models  # noqa: F401 - Register all models with Base.metadata

logger = logging.getLogger(__name__)

MIGRATION_STATEMENTS = [
    # USERS table columns
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS designation VARCHAR(100);",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS login_id VARCHAR(100);",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT false;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions JSON;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT false;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT false;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code_hash VARCHAR(255);",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_code_expires_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_attempts INTEGER NOT NULL DEFAULT 0;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_last_sent_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by_id UUID REFERENCES users(id);",
    "ALTER TABLE users ALTER COLUMN email DROP NOT NULL;",

    # USERS auto_id identity column & unique constraint
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_name = 'users' AND column_name = 'auto_id'
        ) THEN
            ALTER TABLE users ADD COLUMN auto_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001);
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_auto_id'
        ) THEN
            ALTER TABLE users ADD CONSTRAINT uq_users_auto_id UNIQUE (auto_id);
        END IF;
    END $$;
    """,

    # BUSINESSES table columns
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'PENDING';",
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(500);",
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS subscription_plan_id UUID;",
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS plan_expires_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE businesses ADD COLUMN IF NOT EXISTS subscription_notes VARCHAR(500);",

    # BUSINESS_SETTINGS table columns
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS city VARCHAR(100);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS state VARCHAR(100);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS gst_number VARCHAR(50);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS opening_time VARCHAR(20) DEFAULT '09:00 AM';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS closing_time VARCHAR(20) DEFAULT '10:00 PM';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS website VARCHAR(255);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS whatsapp_number VARCHAR(20);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS default_country_code VARCHAR(10) NOT NULL DEFAULT '+91';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS default_message_signature VARCHAR(255);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_whatsapp_campaigns BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_welcome_messages BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS review_link VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS maps_link VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS booking_link VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS invoice_prefix VARCHAR(20) NOT NULL DEFAULT 'INV-';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS invoice_footer VARCHAR(255);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS show_gst_on_invoice BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS show_qr_on_invoice BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS auto_print_invoice BOOLEAN NOT NULL DEFAULT false;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS receipt_paper_size VARCHAR(20) NOT NULL DEFAULT '80mm';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS round_off_bill BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS next_order_number INTEGER NOT NULL DEFAULT 1;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS notify_orders BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS notify_qr_orders BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS notify_campaigns BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS notify_reviews BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS notify_email BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS ai_default_tone VARCHAR(50) NOT NULL DEFAULT 'Friendly';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS ai_max_monthly_requests INTEGER NOT NULL DEFAULT 500;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS ai_requests_used_month INTEGER NOT NULL DEFAULT 0;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS ai_monthly_used_credits INTEGER NOT NULL DEFAULT 0;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS purchased_ai_credits INTEGER NOT NULL DEFAULT 0;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS ai_usage_period VARCHAR(20);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS last_ai_activity_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_qr_ordering BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_staff_ordering BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_parcel BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_takeaway BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS enable_dine_in BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS pos_auto_complete_order BOOLEAN NOT NULL DEFAULT false;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS pos_auto_free_table BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS pos_default_payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS allow_guest_checkout BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS payment_qr_image VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS payment_upi_id VARCHAR(100);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS payment_payee_name VARCHAR(100);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS logo VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS cover_image VARCHAR(500);",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS default_discount FLOAT NOT NULL DEFAULT 0.0;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS recovery_enabled BOOLEAN NOT NULL DEFAULT true;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS recovery_buckets VARCHAR(50) NOT NULL DEFAULT '15,30,45,60,90';",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS recovery_cooldown_days INTEGER NOT NULL DEFAULT 7;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS recovery_max_messages_per_day INTEGER NOT NULL DEFAULT 100;",
    "ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS recovery_window_days INTEGER NOT NULL DEFAULT 30;",

    # ORDERS table columns
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS visit_token VARCHAR(255);",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP WITH TIME ZONE;",
    "ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_number INTEGER;",

    # ORDER_ITEMS table columns
    "ALTER TABLE order_items ADD COLUMN IF NOT EXISTS menu_item_id UUID;",
    "ALTER TABLE order_items ADD COLUMN IF NOT EXISTS tax_rate FLOAT NOT NULL DEFAULT 0.0;",
    "ALTER TABLE order_items ADD COLUMN IF NOT EXISTS discount FLOAT NOT NULL DEFAULT 0.0;",

    # SUBSCRIPTION_PLANS table columns
    "ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS max_active_devices INTEGER NOT NULL DEFAULT 1;",

    # PLATFORM_SETTINGS table columns
    "ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS support_phone VARCHAR(20);",

    # EMAIL_OTPS table creation if missing
    """
    CREATE TABLE IF NOT EXISTS email_otps (
        id UUID PRIMARY KEY,
        email VARCHAR(150) NOT NULL,
        hashed_otp VARCHAR(255) NOT NULL,
        expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
        attempts INTEGER NOT NULL DEFAULT 0,
        is_used BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
    );
    """,
    "CREATE INDEX IF NOT EXISTS ix_email_otps_email ON email_otps (email);",

]


def sync_database_schema(engine: Engine) -> dict:
    """
    Idempotently synchronizes the database tables and columns with current SQLAlchemy models.
    Safe for production: uses ADD COLUMN IF NOT EXISTS and CREATE TABLE IF NOT EXISTS.
    Never drops tables, never drops columns, and never alters existing data destructively.
    """
    logger.info("==> [SchemaSync] Starting idempotent database schema synchronization...")
    
    # 1. Create any missing tables defined across models
    try:
        Base.metadata.create_all(bind=engine)
        logger.info("==> [SchemaSync] Base.metadata.create_all executed successfully.")
    except Exception as exc:
        logger.warning("==> [SchemaSync] Base.metadata.create_all warning: %s", exc)

    executed_count = 0
    warnings = []

    # 2. Execute idempotent column additions and constraints
    with engine.begin() as conn:
        for stmt in MIGRATION_STATEMENTS:
            cleaned_stmt = stmt.strip()
            if not cleaned_stmt:
                continue
            try:
                conn.execute(text(cleaned_stmt))
                executed_count += 1
            except Exception as exc:
                first_line = cleaned_stmt.splitlines()[0][:60]
                logger.warning("==> [SchemaSync] Statement warning (%s...): %s", first_line, exc)
                warnings.append(f"{first_line}: {str(exc)}")

    # 3. Verify columns on users table
    insp = inspect(engine)
    user_cols = [c["name"] for c in insp.get_columns("users")]
    logger.info(
        "==> [SchemaSync] Complete! 'users' table has %d columns.",
        len(user_cols),
    )

    return {
        "status": "success",
        "executed_statements": executed_count,
        "users_columns_count": len(user_cols),
        "warnings": warnings,
    }
