"""add_menu_categories_and_menu_items

Revision ID: 0b1fe2e97458
Revises: 1b11f15eefe1
Create Date: 2026-07-27 16:42:51.672886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1fe2e97458'
down_revision: Union[str, Sequence[str], None] = '1b11f15eefe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
