"""add_max_active_devices_to_subscription_plans

Revision ID: 146c8455eae0
Revises: c68c94683c98
Create Date: 2026-07-27 13:58:37.812116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146c8455eae0'
down_revision: Union[str, Sequence[str], None] = 'c68c94683c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('subscription_plans', sa.Column('max_active_devices', sa.Integer(), server_default='5', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'max_active_devices')
    # ### end Alembic commands ###
