"""create_message_templates_table

Revision ID: 17a3803341fa
Revises: f071b9b01781
Create Date: 2026-07-23 14:54:15.448228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a3803341fa'
down_revision: Union[str, Sequence[str], None] = 'f071b9b01781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('campaign_type', sa.Enum('BIRTHDAY', 'ANNIVERSARY', 'WELCOME', 'RECOVERY', 'FESTIVAL', 'VIP', 'CUSTOM', name='campaigntype', native_enum=False), nullable=False),
    sa.Column('template_name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'campaign_type', name='uq_business_campaign_type_template')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_templates')
    # ### end Alembic commands ###
