"""add_menu_item_id_tax_rate_discount_to_order_items

Revision ID: 1b11f15eefe1
Revises: 117c32560f5b
Create Date: 2026-07-27 16:34:21.470297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b11f15eefe1'
down_revision: Union[str, Sequence[str], None] = '117c32560f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('menu_item_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('tax_rate', sa.Float(), nullable=False))
    op.add_column('order_items', sa.Column('discount', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'services', ['menu_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'discount')
    op.drop_column('order_items', 'tax_rate')
    op.drop_column('order_items', 'menu_item_id')
    # ### end Alembic commands ###
