"""add_dining_areas_and_restaurant_tables

Revision ID: 796cdfbbf93f
Revises: 146c8455eae0
Create Date: 2026-07-27 16:03:40.451025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796cdfbbf93f'
down_revision: Union[str, Sequence[str], None] = '146c8455eae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
