"""create_business_settings_table

Revision ID: 7cc6d4823ec2
Revises: 17a3803341fa
Create Date: 2026-07-23 15:01:28.593603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc6d4823ec2'
down_revision: Union[str, Sequence[str], None] = '17a3803341fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('service_charge', sa.Float(), nullable=False),
    sa.Column('payment_qr_image', sa.String(length=500), nullable=True),
    sa.Column('payment_upi_id', sa.String(length=100), nullable=True),
    sa.Column('default_discount', sa.Float(), nullable=False),
    sa.Column('review_link', sa.String(length=500), nullable=True),
    sa.Column('booking_link', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_settings')
    # ### end Alembic commands ###
