"""add_review_booster_columns

Revision ID: e5d15e4e04e4
Revises: f383f7b9c37d
Create Date: 2026-07-31 00:00:16.458140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d15e4e04e4'
down_revision: Union[str, Sequence[str], None] = 'f383f7b9c37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column(
        'review_booster_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')
    ))
    op.add_column('business_settings', sa.Column(
        'review_booster_cooldown_days', sa.Integer(), nullable=False, server_default=sa.text('7')
    ))
    op.add_column('business_settings', sa.Column(
        'review_booster_auto_send', sa.Boolean(), nullable=False, server_default=sa.text('false')
    ))
    op.add_column('business_settings', sa.Column(
        'review_booster_ai_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')
    ))
    op.add_column('campaign_logs', sa.Column('visit_id', sa.UUID(), nullable=True))
    op.add_column('campaign_logs', sa.Column('tracking_token', sa.String(length=100), nullable=True))
    op.add_column('campaign_logs', sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_logs', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_logs', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaign_logs_tracking_token'), 'campaign_logs', ['tracking_token'], unique=False)
    op.create_foreign_key(None, 'campaign_logs', 'visits', ['visit_id'], ['id'])
    op.create_foreign_key(None, 'campaign_logs', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign_logs', type_='foreignkey')
    op.drop_constraint(None, 'campaign_logs', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_logs_tracking_token'), table_name='campaign_logs')
    op.drop_column('campaign_logs', 'reviewed_by')
    op.drop_column('campaign_logs', 'reviewed_at')
    op.drop_column('campaign_logs', 'clicked_at')
    op.drop_column('campaign_logs', 'tracking_token')
    op.drop_column('campaign_logs', 'visit_id')
    op.drop_column('business_settings', 'review_booster_ai_enabled')
    op.drop_column('business_settings', 'review_booster_auto_send')
    op.drop_column('business_settings', 'review_booster_cooldown_days')
    op.drop_column('business_settings', 'review_booster_enabled')
    # ### end Alembic commands ###
