"""create_automation_rules_table

Revision ID: f071b9b01781
Revises: cde64e621d13
Create Date: 2026-07-23 13:40:15.869157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f071b9b01781'
down_revision: Union[str, Sequence[str], None] = 'cde64e621d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('campaign_type', sa.Enum('BIRTHDAY', 'ANNIVERSARY', 'WELCOME', 'RECOVERY', 'FESTIVAL', 'VIP', 'CUSTOM', name='campaigntype', native_enum=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY', name='scheduletype', native_enum=False), nullable=False),
    sa.Column('run_time', sa.String(length=10), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'campaign_type', name='uq_business_campaign_type_automation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
