"""add_recovery_settings_to_business_settings

Revision ID: f383f7b9c37d
Revises: c98170d84ae7
Create Date: 2026-07-30 22:41:50.979351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f383f7b9c37d'
down_revision: Union[str, Sequence[str], None] = 'c98170d84ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_settings', sa.Column(
        'recovery_enabled', sa.Boolean(), nullable=False,
        server_default=sa.text('true')
    ))
    op.add_column('business_settings', sa.Column(
        'recovery_buckets', sa.String(length=50), nullable=False,
        server_default=sa.text("'15,30,45,60,90'")
    ))
    op.add_column('business_settings', sa.Column(
        'recovery_cooldown_days', sa.Integer(), nullable=False,
        server_default=sa.text('7')
    ))
    op.add_column('business_settings', sa.Column(
        'recovery_max_messages_per_day', sa.Integer(), nullable=False,
        server_default=sa.text('100')
    ))
    op.add_column('business_settings', sa.Column(
        'recovery_window_days', sa.Integer(), nullable=False,
        server_default=sa.text('30')
    ))
    op.alter_column('business_settings', 'enable_qr_ordering',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_staff_ordering',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_parcel',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_takeaway',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'INV-'::character varying"))
    # drop_index only if index exists — skip if not present
    try:
        op.drop_index(op.f('uq_order_menu_item'), table_name='order_items', postgresql_where='(menu_item_id IS NOT NULL)')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_order_menu_item'), 'order_items', ['order_id', 'menu_item_id'], unique=True, postgresql_where='(menu_item_id IS NOT NULL)')
    op.alter_column('business_settings', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'INV-'::character varying"))
    op.alter_column('business_settings', 'enable_takeaway',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_parcel',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_staff_ordering',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('business_settings', 'enable_qr_ordering',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('business_settings', 'recovery_window_days')
    op.drop_column('business_settings', 'recovery_max_messages_per_day')
    op.drop_column('business_settings', 'recovery_cooldown_days')
    op.drop_column('business_settings', 'recovery_buckets')
    op.drop_column('business_settings', 'recovery_enabled')
    # ### end Alembic commands ###
