"""add_status_rejection_reason_approved_at_to_businesses

Revision ID: fa1eb01c537f
Revises: 7cc6d4823ec2
Create Date: 2026-07-26 20:39:28.217905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1eb01c537f'
down_revision: Union[str, Sequence[str], None] = '7cc6d4823ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('status', sa.String(length=30), server_default='PENDING', nullable=False))
    op.add_column('businesses', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('businesses', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'approved_at')
    op.drop_column('businesses', 'rejection_reason')
    op.drop_column('businesses', 'status')
    # ### end Alembic commands ###
