"""add_subscription_plans_table_and_business_subscription_fields

Revision ID: fcfe25b99152
Revises: fa1eb01c537f
Create Date: 2026-07-26 20:58:08.222437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfe25b99152'
down_revision: Union[str, Sequence[str], None] = 'fa1eb01c537f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('subscription_plan_id', sa.UUID(), nullable=True))
    op.add_column('businesses', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('subscription_notes', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'businesses', 'subscription_plans', ['subscription_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'subscription_notes')
    op.drop_column('businesses', 'plan_expires_at')
    op.drop_column('businesses', 'subscription_plan_id')
    # ### end Alembic commands ###
