from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class UserBase(BaseModel):
    name: str
    email: str | None = None


class UserCreate(UserBase):
    password: str


class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    business_id: UUID
    role: str
    phone: str | None = None
    designation: str | None = None
    login_id: str | None = None
    status: str = "ACTIVE"
    is_active: bool = True
    permissions: list[str] | None = None
    last_login: datetime | None = None


# ---------------------------------------------------------------------------
# Staff Management Schemas
# ---------------------------------------------------------------------------

class StaffCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=150)
    phone: str = Field(..., min_length=1, max_length=50)
    email: str | None = Field(default=None)
    designation: str | None = Field(default=None, max_length=100)
    login_id: str | None = Field(default=None, max_length=100, description="Auto-generated by backend if omitted")
    password: str = Field(..., min_length=6)
    status: str = Field(default="ACTIVE")
    permissions: list[str] = Field(default_factory=list)


class StaffUpdate(BaseModel):
    name: str | None = Field(default=None, max_length=150)
    phone: str | None = Field(default=None, max_length=50)
    email: str | None = Field(default=None)
    designation: str | None = Field(default=None, max_length=100)
    login_id: str | None = Field(default=None, max_length=100)
    password: str | None = Field(default=None, min_length=6)
    status: str | None = Field(default=None)
    permissions: list[str] | None = Field(default=None)


class StaffResetPassword(BaseModel):
    password: str = Field(..., min_length=6)


class StaffStatusToggle(BaseModel):
    status: str = Field(..., description="ACTIVE or INACTIVE")


class StaffResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    business_id: UUID
    name: str
    phone: str | None = None
    email: str | None = None
    designation: str | None = None
    login_id: str | None = None
    role: str
    status: str
    is_active: bool
    permissions: list[str] | None = None
    last_login: datetime | None = None
    created_at: datetime


class PaginatedStaffResponse(BaseModel):
    items: list[StaffResponse]
    total: int
    page: int
    limit: int
    pages: int