/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as LoginBusinessRouteImport } from './routes/login.business'
import { Route as QrTableRouteImport } from './routes/qr.$table'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AppTypeBusinessRouteImport } from './routes/app.$type.$business'
import { Route as QrBusinessTableRouteImport } from './routes/qr.$business.$table'
import { Route as AppTypeBusinessAppointmentsRouteImport } from './routes/app.$type.$business.appointments'
import { Route as AppTypeBusinessBookingsRouteImport } from './routes/app.$type.$business.bookings'
import { Route as AppTypeBusinessCalendarRouteImport } from './routes/app.$type.$business.calendar'
import { Route as AppTypeBusinessCouponsRouteImport } from './routes/app.$type.$business.coupons'
import { Route as AppTypeBusinessCustomerRecoveryRouteImport } from './routes/app.$type.$business.customer-recovery'
import { Route as AppTypeBusinessDashboardRouteImport } from './routes/app.$type.$business.dashboard'
import { Route as AppTypeBusinessFestivalCampaignsRouteImport } from './routes/app.$type.$business.festival-campaigns'
import { Route as AppTypeBusinessLoyaltyRouteImport } from './routes/app.$type.$business.loyalty'
import { Route as AppTypeBusinessMarketingRouteImport } from './routes/app.$type.$business.marketing'
import { Route as AppTypeBusinessMenuRouteImport } from './routes/app.$type.$business.menu'
import { Route as AppTypeBusinessOrdersRouteImport } from './routes/app.$type.$business.orders'
import { Route as AppTypeBusinessReportsRouteImport } from './routes/app.$type.$business.reports'
import { Route as AppTypeBusinessRevenueRouteImport } from './routes/app.$type.$business.revenue'
import { Route as AppTypeBusinessReviewBoosterRouteImport } from './routes/app.$type.$business.review-booster'
import { Route as AppTypeBusinessServicesRouteImport } from './routes/app.$type.$business.services'
import { Route as AppTypeBusinessSettingsRouteImport } from './routes/app.$type.$business.settings'
import { Route as AppTypeBusinessSubscriptionRouteImport } from './routes/app.$type.$business.subscription'
import { Route as AppTypeBusinessTablesRouteImport } from './routes/app.$type.$business.tables'
import { Route as AppTypeBusinessTeamRouteImport } from './routes/app.$type.$business.team'
import { Route as AppTypeBusinessTemplatesRouteImport } from './routes/app.$type.$business.templates'
import { Route as AppTypeBusinessVipRouteImport } from './routes/app.$type.$business.vip'
import { Route as AppTypeBusinessWelcomeRouteImport } from './routes/app.$type.$business.welcome'
import { Route as AppTypeBusinessWhatsappCampaignsRouteImport } from './routes/app.$type.$business.whatsapp-campaigns'
import { Route as AppTypeBusinessWhatsappHistoryRouteImport } from './routes/app.$type.$business.whatsapp-history'
import { Route as AppTypeBusinessAnniversaryCampaignsIndexRouteImport } from './routes/app.$type.$business.anniversary-campaigns.index'
import { Route as AppTypeBusinessAnniversaryCampaignsMonthRouteImport } from './routes/app.$type.$business.anniversary-campaigns.month'
import { Route as AppTypeBusinessAnniversaryCampaignsTodayRouteImport } from './routes/app.$type.$business.anniversary-campaigns.today'
import { Route as AppTypeBusinessAnniversaryCampaignsTomorrowRouteImport } from './routes/app.$type.$business.anniversary-campaigns.tomorrow'
import { Route as AppTypeBusinessAnniversaryCampaignsWeekRouteImport } from './routes/app.$type.$business.anniversary-campaigns.week'
import { Route as AppTypeBusinessBirthdayCampaignsIndexRouteImport } from './routes/app.$type.$business.birthday-campaigns.index'
import { Route as AppTypeBusinessBirthdayCampaignsMonthRouteImport } from './routes/app.$type.$business.birthday-campaigns.month'
import { Route as AppTypeBusinessBirthdayCampaignsTodayRouteImport } from './routes/app.$type.$business.birthday-campaigns.today'
import { Route as AppTypeBusinessBirthdayCampaignsTomorrowRouteImport } from './routes/app.$type.$business.birthday-campaigns.tomorrow'
import { Route as AppTypeBusinessBirthdayCampaignsWeekRouteImport } from './routes/app.$type.$business.birthday-campaigns.week'
import { Route as AppTypeBusinessCustomerRecoveryDaysRouteImport } from './routes/app.$type.$business.customer-recovery.$days'
import { Route as AppTypeBusinessCustomersIndexRouteImport } from './routes/app.$type.$business.customers.index'
import { Route as AppTypeBusinessCustomersIdRouteImport } from './routes/app.$type.$business.customers.$id'
import { Route as AppTypeBusinessOrdersIdRouteImport } from './routes/app.$type.$business.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBusinessRoute = LoginBusinessRouteImport.update({
  id: '/login/business',
  path: '/login/business',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTableRoute = QrTableRouteImport.update({
  id: '/qr/$table',
  path: '/qr/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppTypeBusinessRoute = AppTypeBusinessRouteImport.update({
  id: '/app/$type/$business',
  path: '/app/$type/$business',
  getParentRoute: () => rootRouteImport,
} as any)
const QrBusinessTableRoute = QrBusinessTableRouteImport.update({
  id: '/qr/$business/$table',
  path: '/qr/$business/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTypeBusinessAppointmentsRoute =
  AppTypeBusinessAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBookingsRoute = AppTypeBusinessBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessCalendarRoute = AppTypeBusinessCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessCouponsRoute = AppTypeBusinessCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessCustomerRecoveryRoute =
  AppTypeBusinessCustomerRecoveryRouteImport.update({
    id: '/customer-recovery',
    path: '/customer-recovery',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessDashboardRoute =
  AppTypeBusinessDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessFestivalCampaignsRoute =
  AppTypeBusinessFestivalCampaignsRouteImport.update({
    id: '/festival-campaigns',
    path: '/festival-campaigns',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessLoyaltyRoute = AppTypeBusinessLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessMarketingRoute =
  AppTypeBusinessMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessMenuRoute = AppTypeBusinessMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessOrdersRoute = AppTypeBusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessReportsRoute = AppTypeBusinessReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessRevenueRoute = AppTypeBusinessRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessReviewBoosterRoute =
  AppTypeBusinessReviewBoosterRouteImport.update({
    id: '/review-booster',
    path: '/review-booster',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessServicesRoute = AppTypeBusinessServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessSettingsRoute = AppTypeBusinessSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessSubscriptionRoute =
  AppTypeBusinessSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessTablesRoute = AppTypeBusinessTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessTeamRoute = AppTypeBusinessTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessTemplatesRoute =
  AppTypeBusinessTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessVipRoute = AppTypeBusinessVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessWelcomeRoute = AppTypeBusinessWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppTypeBusinessRoute,
} as any)
const AppTypeBusinessWhatsappCampaignsRoute =
  AppTypeBusinessWhatsappCampaignsRouteImport.update({
    id: '/whatsapp-campaigns',
    path: '/whatsapp-campaigns',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessWhatsappHistoryRoute =
  AppTypeBusinessWhatsappHistoryRouteImport.update({
    id: '/whatsapp-history',
    path: '/whatsapp-history',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessAnniversaryCampaignsIndexRoute =
  AppTypeBusinessAnniversaryCampaignsIndexRouteImport.update({
    id: '/anniversary-campaigns/',
    path: '/anniversary-campaigns/',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessAnniversaryCampaignsMonthRoute =
  AppTypeBusinessAnniversaryCampaignsMonthRouteImport.update({
    id: '/anniversary-campaigns/month',
    path: '/anniversary-campaigns/month',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessAnniversaryCampaignsTodayRoute =
  AppTypeBusinessAnniversaryCampaignsTodayRouteImport.update({
    id: '/anniversary-campaigns/today',
    path: '/anniversary-campaigns/today',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessAnniversaryCampaignsTomorrowRoute =
  AppTypeBusinessAnniversaryCampaignsTomorrowRouteImport.update({
    id: '/anniversary-campaigns/tomorrow',
    path: '/anniversary-campaigns/tomorrow',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessAnniversaryCampaignsWeekRoute =
  AppTypeBusinessAnniversaryCampaignsWeekRouteImport.update({
    id: '/anniversary-campaigns/week',
    path: '/anniversary-campaigns/week',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBirthdayCampaignsIndexRoute =
  AppTypeBusinessBirthdayCampaignsIndexRouteImport.update({
    id: '/birthday-campaigns/',
    path: '/birthday-campaigns/',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBirthdayCampaignsMonthRoute =
  AppTypeBusinessBirthdayCampaignsMonthRouteImport.update({
    id: '/birthday-campaigns/month',
    path: '/birthday-campaigns/month',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBirthdayCampaignsTodayRoute =
  AppTypeBusinessBirthdayCampaignsTodayRouteImport.update({
    id: '/birthday-campaigns/today',
    path: '/birthday-campaigns/today',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBirthdayCampaignsTomorrowRoute =
  AppTypeBusinessBirthdayCampaignsTomorrowRouteImport.update({
    id: '/birthday-campaigns/tomorrow',
    path: '/birthday-campaigns/tomorrow',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessBirthdayCampaignsWeekRoute =
  AppTypeBusinessBirthdayCampaignsWeekRouteImport.update({
    id: '/birthday-campaigns/week',
    path: '/birthday-campaigns/week',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessCustomerRecoveryDaysRoute =
  AppTypeBusinessCustomerRecoveryDaysRouteImport.update({
    id: '/$days',
    path: '/$days',
    getParentRoute: () => AppTypeBusinessCustomerRecoveryRoute,
  } as any)
const AppTypeBusinessCustomersIndexRoute =
  AppTypeBusinessCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessCustomersIdRoute =
  AppTypeBusinessCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AppTypeBusinessRoute,
  } as any)
const AppTypeBusinessOrdersIdRoute = AppTypeBusinessOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTypeBusinessOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/business': typeof LoginBusinessRoute
  '/qr/$table': typeof QrTableRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/$type/$business': typeof AppTypeBusinessRouteWithChildren
  '/qr/$business/$table': typeof QrBusinessTableRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/app/$type/$business/appointments': typeof AppTypeBusinessAppointmentsRoute
  '/app/$type/$business/bookings': typeof AppTypeBusinessBookingsRoute
  '/app/$type/$business/calendar': typeof AppTypeBusinessCalendarRoute
  '/app/$type/$business/coupons': typeof AppTypeBusinessCouponsRoute
  '/app/$type/$business/customer-recovery': typeof AppTypeBusinessCustomerRecoveryRouteWithChildren
  '/app/$type/$business/dashboard': typeof AppTypeBusinessDashboardRoute
  '/app/$type/$business/festival-campaigns': typeof AppTypeBusinessFestivalCampaignsRoute
  '/app/$type/$business/loyalty': typeof AppTypeBusinessLoyaltyRoute
  '/app/$type/$business/marketing': typeof AppTypeBusinessMarketingRoute
  '/app/$type/$business/menu': typeof AppTypeBusinessMenuRoute
  '/app/$type/$business/orders': typeof AppTypeBusinessOrdersRouteWithChildren
  '/app/$type/$business/reports': typeof AppTypeBusinessReportsRoute
  '/app/$type/$business/revenue': typeof AppTypeBusinessRevenueRoute
  '/app/$type/$business/review-booster': typeof AppTypeBusinessReviewBoosterRoute
  '/app/$type/$business/services': typeof AppTypeBusinessServicesRoute
  '/app/$type/$business/settings': typeof AppTypeBusinessSettingsRoute
  '/app/$type/$business/subscription': typeof AppTypeBusinessSubscriptionRoute
  '/app/$type/$business/tables': typeof AppTypeBusinessTablesRoute
  '/app/$type/$business/team': typeof AppTypeBusinessTeamRoute
  '/app/$type/$business/templates': typeof AppTypeBusinessTemplatesRoute
  '/app/$type/$business/vip': typeof AppTypeBusinessVipRoute
  '/app/$type/$business/welcome': typeof AppTypeBusinessWelcomeRoute
  '/app/$type/$business/whatsapp-campaigns': typeof AppTypeBusinessWhatsappCampaignsRoute
  '/app/$type/$business/whatsapp-history': typeof AppTypeBusinessWhatsappHistoryRoute
  '/app/$type/$business/anniversary-campaigns/month': typeof AppTypeBusinessAnniversaryCampaignsMonthRoute
  '/app/$type/$business/anniversary-campaigns/today': typeof AppTypeBusinessAnniversaryCampaignsTodayRoute
  '/app/$type/$business/anniversary-campaigns/tomorrow': typeof AppTypeBusinessAnniversaryCampaignsTomorrowRoute
  '/app/$type/$business/anniversary-campaigns/week': typeof AppTypeBusinessAnniversaryCampaignsWeekRoute
  '/app/$type/$business/birthday-campaigns/month': typeof AppTypeBusinessBirthdayCampaignsMonthRoute
  '/app/$type/$business/birthday-campaigns/today': typeof AppTypeBusinessBirthdayCampaignsTodayRoute
  '/app/$type/$business/birthday-campaigns/tomorrow': typeof AppTypeBusinessBirthdayCampaignsTomorrowRoute
  '/app/$type/$business/birthday-campaigns/week': typeof AppTypeBusinessBirthdayCampaignsWeekRoute
  '/app/$type/$business/customer-recovery/$days': typeof AppTypeBusinessCustomerRecoveryDaysRoute
  '/app/$type/$business/customers/$id': typeof AppTypeBusinessCustomersIdRoute
  '/app/$type/$business/orders/$id': typeof AppTypeBusinessOrdersIdRoute
  '/app/$type/$business/anniversary-campaigns/': typeof AppTypeBusinessAnniversaryCampaignsIndexRoute
  '/app/$type/$business/birthday-campaigns/': typeof AppTypeBusinessBirthdayCampaignsIndexRoute
  '/app/$type/$business/customers/': typeof AppTypeBusinessCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/business': typeof LoginBusinessRoute
  '/qr/$table': typeof QrTableRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/$type/$business': typeof AppTypeBusinessRouteWithChildren
  '/qr/$business/$table': typeof QrBusinessTableRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/app/$type/$business/appointments': typeof AppTypeBusinessAppointmentsRoute
  '/app/$type/$business/bookings': typeof AppTypeBusinessBookingsRoute
  '/app/$type/$business/calendar': typeof AppTypeBusinessCalendarRoute
  '/app/$type/$business/coupons': typeof AppTypeBusinessCouponsRoute
  '/app/$type/$business/customer-recovery': typeof AppTypeBusinessCustomerRecoveryRouteWithChildren
  '/app/$type/$business/dashboard': typeof AppTypeBusinessDashboardRoute
  '/app/$type/$business/festival-campaigns': typeof AppTypeBusinessFestivalCampaignsRoute
  '/app/$type/$business/loyalty': typeof AppTypeBusinessLoyaltyRoute
  '/app/$type/$business/marketing': typeof AppTypeBusinessMarketingRoute
  '/app/$type/$business/menu': typeof AppTypeBusinessMenuRoute
  '/app/$type/$business/orders': typeof AppTypeBusinessOrdersRouteWithChildren
  '/app/$type/$business/reports': typeof AppTypeBusinessReportsRoute
  '/app/$type/$business/revenue': typeof AppTypeBusinessRevenueRoute
  '/app/$type/$business/review-booster': typeof AppTypeBusinessReviewBoosterRoute
  '/app/$type/$business/services': typeof AppTypeBusinessServicesRoute
  '/app/$type/$business/settings': typeof AppTypeBusinessSettingsRoute
  '/app/$type/$business/subscription': typeof AppTypeBusinessSubscriptionRoute
  '/app/$type/$business/tables': typeof AppTypeBusinessTablesRoute
  '/app/$type/$business/team': typeof AppTypeBusinessTeamRoute
  '/app/$type/$business/templates': typeof AppTypeBusinessTemplatesRoute
  '/app/$type/$business/vip': typeof AppTypeBusinessVipRoute
  '/app/$type/$business/welcome': typeof AppTypeBusinessWelcomeRoute
  '/app/$type/$business/whatsapp-campaigns': typeof AppTypeBusinessWhatsappCampaignsRoute
  '/app/$type/$business/whatsapp-history': typeof AppTypeBusinessWhatsappHistoryRoute
  '/app/$type/$business/anniversary-campaigns/month': typeof AppTypeBusinessAnniversaryCampaignsMonthRoute
  '/app/$type/$business/anniversary-campaigns/today': typeof AppTypeBusinessAnniversaryCampaignsTodayRoute
  '/app/$type/$business/anniversary-campaigns/tomorrow': typeof AppTypeBusinessAnniversaryCampaignsTomorrowRoute
  '/app/$type/$business/anniversary-campaigns/week': typeof AppTypeBusinessAnniversaryCampaignsWeekRoute
  '/app/$type/$business/birthday-campaigns/month': typeof AppTypeBusinessBirthdayCampaignsMonthRoute
  '/app/$type/$business/birthday-campaigns/today': typeof AppTypeBusinessBirthdayCampaignsTodayRoute
  '/app/$type/$business/birthday-campaigns/tomorrow': typeof AppTypeBusinessBirthdayCampaignsTomorrowRoute
  '/app/$type/$business/birthday-campaigns/week': typeof AppTypeBusinessBirthdayCampaignsWeekRoute
  '/app/$type/$business/customer-recovery/$days': typeof AppTypeBusinessCustomerRecoveryDaysRoute
  '/app/$type/$business/customers/$id': typeof AppTypeBusinessCustomersIdRoute
  '/app/$type/$business/orders/$id': typeof AppTypeBusinessOrdersIdRoute
  '/app/$type/$business/anniversary-campaigns': typeof AppTypeBusinessAnniversaryCampaignsIndexRoute
  '/app/$type/$business/birthday-campaigns': typeof AppTypeBusinessBirthdayCampaignsIndexRoute
  '/app/$type/$business/customers': typeof AppTypeBusinessCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/business': typeof LoginBusinessRoute
  '/qr/$table': typeof QrTableRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/app/$type/$business': typeof AppTypeBusinessRouteWithChildren
  '/qr/$business/$table': typeof QrBusinessTableRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/app/$type/$business/appointments': typeof AppTypeBusinessAppointmentsRoute
  '/app/$type/$business/bookings': typeof AppTypeBusinessBookingsRoute
  '/app/$type/$business/calendar': typeof AppTypeBusinessCalendarRoute
  '/app/$type/$business/coupons': typeof AppTypeBusinessCouponsRoute
  '/app/$type/$business/customer-recovery': typeof AppTypeBusinessCustomerRecoveryRouteWithChildren
  '/app/$type/$business/dashboard': typeof AppTypeBusinessDashboardRoute
  '/app/$type/$business/festival-campaigns': typeof AppTypeBusinessFestivalCampaignsRoute
  '/app/$type/$business/loyalty': typeof AppTypeBusinessLoyaltyRoute
  '/app/$type/$business/marketing': typeof AppTypeBusinessMarketingRoute
  '/app/$type/$business/menu': typeof AppTypeBusinessMenuRoute
  '/app/$type/$business/orders': typeof AppTypeBusinessOrdersRouteWithChildren
  '/app/$type/$business/reports': typeof AppTypeBusinessReportsRoute
  '/app/$type/$business/revenue': typeof AppTypeBusinessRevenueRoute
  '/app/$type/$business/review-booster': typeof AppTypeBusinessReviewBoosterRoute
  '/app/$type/$business/services': typeof AppTypeBusinessServicesRoute
  '/app/$type/$business/settings': typeof AppTypeBusinessSettingsRoute
  '/app/$type/$business/subscription': typeof AppTypeBusinessSubscriptionRoute
  '/app/$type/$business/tables': typeof AppTypeBusinessTablesRoute
  '/app/$type/$business/team': typeof AppTypeBusinessTeamRoute
  '/app/$type/$business/templates': typeof AppTypeBusinessTemplatesRoute
  '/app/$type/$business/vip': typeof AppTypeBusinessVipRoute
  '/app/$type/$business/welcome': typeof AppTypeBusinessWelcomeRoute
  '/app/$type/$business/whatsapp-campaigns': typeof AppTypeBusinessWhatsappCampaignsRoute
  '/app/$type/$business/whatsapp-history': typeof AppTypeBusinessWhatsappHistoryRoute
  '/app/$type/$business/anniversary-campaigns/month': typeof AppTypeBusinessAnniversaryCampaignsMonthRoute
  '/app/$type/$business/anniversary-campaigns/today': typeof AppTypeBusinessAnniversaryCampaignsTodayRoute
  '/app/$type/$business/anniversary-campaigns/tomorrow': typeof AppTypeBusinessAnniversaryCampaignsTomorrowRoute
  '/app/$type/$business/anniversary-campaigns/week': typeof AppTypeBusinessAnniversaryCampaignsWeekRoute
  '/app/$type/$business/birthday-campaigns/month': typeof AppTypeBusinessBirthdayCampaignsMonthRoute
  '/app/$type/$business/birthday-campaigns/today': typeof AppTypeBusinessBirthdayCampaignsTodayRoute
  '/app/$type/$business/birthday-campaigns/tomorrow': typeof AppTypeBusinessBirthdayCampaignsTomorrowRoute
  '/app/$type/$business/birthday-campaigns/week': typeof AppTypeBusinessBirthdayCampaignsWeekRoute
  '/app/$type/$business/customer-recovery/$days': typeof AppTypeBusinessCustomerRecoveryDaysRoute
  '/app/$type/$business/customers/$id': typeof AppTypeBusinessCustomersIdRoute
  '/app/$type/$business/orders/$id': typeof AppTypeBusinessOrdersIdRoute
  '/app/$type/$business/anniversary-campaigns/': typeof AppTypeBusinessAnniversaryCampaignsIndexRoute
  '/app/$type/$business/birthday-campaigns/': typeof AppTypeBusinessBirthdayCampaignsIndexRoute
  '/app/$type/$business/customers/': typeof AppTypeBusinessCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/docs'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/admin/approvals'
    | '/admin/monitoring'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/login/admin'
    | '/login/business'
    | '/qr/$table'
    | '/admin/'
    | '/app/'
    | '/login/'
    | '/admin/clients/$id'
    | '/app/$type/$business'
    | '/qr/$business/$table'
    | '/admin/clients/'
    | '/app/$type/$business/appointments'
    | '/app/$type/$business/bookings'
    | '/app/$type/$business/calendar'
    | '/app/$type/$business/coupons'
    | '/app/$type/$business/customer-recovery'
    | '/app/$type/$business/dashboard'
    | '/app/$type/$business/festival-campaigns'
    | '/app/$type/$business/loyalty'
    | '/app/$type/$business/marketing'
    | '/app/$type/$business/menu'
    | '/app/$type/$business/orders'
    | '/app/$type/$business/reports'
    | '/app/$type/$business/revenue'
    | '/app/$type/$business/review-booster'
    | '/app/$type/$business/services'
    | '/app/$type/$business/settings'
    | '/app/$type/$business/subscription'
    | '/app/$type/$business/tables'
    | '/app/$type/$business/team'
    | '/app/$type/$business/templates'
    | '/app/$type/$business/vip'
    | '/app/$type/$business/welcome'
    | '/app/$type/$business/whatsapp-campaigns'
    | '/app/$type/$business/whatsapp-history'
    | '/app/$type/$business/anniversary-campaigns/month'
    | '/app/$type/$business/anniversary-campaigns/today'
    | '/app/$type/$business/anniversary-campaigns/tomorrow'
    | '/app/$type/$business/anniversary-campaigns/week'
    | '/app/$type/$business/birthday-campaigns/month'
    | '/app/$type/$business/birthday-campaigns/today'
    | '/app/$type/$business/birthday-campaigns/tomorrow'
    | '/app/$type/$business/birthday-campaigns/week'
    | '/app/$type/$business/customer-recovery/$days'
    | '/app/$type/$business/customers/$id'
    | '/app/$type/$business/orders/$id'
    | '/app/$type/$business/anniversary-campaigns/'
    | '/app/$type/$business/birthday-campaigns/'
    | '/app/$type/$business/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/admin/approvals'
    | '/admin/monitoring'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/login/admin'
    | '/login/business'
    | '/qr/$table'
    | '/admin'
    | '/app'
    | '/login'
    | '/admin/clients/$id'
    | '/app/$type/$business'
    | '/qr/$business/$table'
    | '/admin/clients'
    | '/app/$type/$business/appointments'
    | '/app/$type/$business/bookings'
    | '/app/$type/$business/calendar'
    | '/app/$type/$business/coupons'
    | '/app/$type/$business/customer-recovery'
    | '/app/$type/$business/dashboard'
    | '/app/$type/$business/festival-campaigns'
    | '/app/$type/$business/loyalty'
    | '/app/$type/$business/marketing'
    | '/app/$type/$business/menu'
    | '/app/$type/$business/orders'
    | '/app/$type/$business/reports'
    | '/app/$type/$business/revenue'
    | '/app/$type/$business/review-booster'
    | '/app/$type/$business/services'
    | '/app/$type/$business/settings'
    | '/app/$type/$business/subscription'
    | '/app/$type/$business/tables'
    | '/app/$type/$business/team'
    | '/app/$type/$business/templates'
    | '/app/$type/$business/vip'
    | '/app/$type/$business/welcome'
    | '/app/$type/$business/whatsapp-campaigns'
    | '/app/$type/$business/whatsapp-history'
    | '/app/$type/$business/anniversary-campaigns/month'
    | '/app/$type/$business/anniversary-campaigns/today'
    | '/app/$type/$business/anniversary-campaigns/tomorrow'
    | '/app/$type/$business/anniversary-campaigns/week'
    | '/app/$type/$business/birthday-campaigns/month'
    | '/app/$type/$business/birthday-campaigns/today'
    | '/app/$type/$business/birthday-campaigns/tomorrow'
    | '/app/$type/$business/birthday-campaigns/week'
    | '/app/$type/$business/customer-recovery/$days'
    | '/app/$type/$business/customers/$id'
    | '/app/$type/$business/orders/$id'
    | '/app/$type/$business/anniversary-campaigns'
    | '/app/$type/$business/birthday-campaigns'
    | '/app/$type/$business/customers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/docs'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/admin/approvals'
    | '/admin/monitoring'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/login/admin'
    | '/login/business'
    | '/qr/$table'
    | '/admin/'
    | '/app/'
    | '/login/'
    | '/admin/clients/$id'
    | '/app/$type/$business'
    | '/qr/$business/$table'
    | '/admin/clients/'
    | '/app/$type/$business/appointments'
    | '/app/$type/$business/bookings'
    | '/app/$type/$business/calendar'
    | '/app/$type/$business/coupons'
    | '/app/$type/$business/customer-recovery'
    | '/app/$type/$business/dashboard'
    | '/app/$type/$business/festival-campaigns'
    | '/app/$type/$business/loyalty'
    | '/app/$type/$business/marketing'
    | '/app/$type/$business/menu'
    | '/app/$type/$business/orders'
    | '/app/$type/$business/reports'
    | '/app/$type/$business/revenue'
    | '/app/$type/$business/review-booster'
    | '/app/$type/$business/services'
    | '/app/$type/$business/settings'
    | '/app/$type/$business/subscription'
    | '/app/$type/$business/tables'
    | '/app/$type/$business/team'
    | '/app/$type/$business/templates'
    | '/app/$type/$business/vip'
    | '/app/$type/$business/welcome'
    | '/app/$type/$business/whatsapp-campaigns'
    | '/app/$type/$business/whatsapp-history'
    | '/app/$type/$business/anniversary-campaigns/month'
    | '/app/$type/$business/anniversary-campaigns/today'
    | '/app/$type/$business/anniversary-campaigns/tomorrow'
    | '/app/$type/$business/anniversary-campaigns/week'
    | '/app/$type/$business/birthday-campaigns/month'
    | '/app/$type/$business/birthday-campaigns/today'
    | '/app/$type/$business/birthday-campaigns/tomorrow'
    | '/app/$type/$business/birthday-campaigns/week'
    | '/app/$type/$business/customer-recovery/$days'
    | '/app/$type/$business/customers/$id'
    | '/app/$type/$business/orders/$id'
    | '/app/$type/$business/anniversary-campaigns/'
    | '/app/$type/$business/birthday-campaigns/'
    | '/app/$type/$business/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  UseCasesRoute: typeof UseCasesRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginBusinessRoute: typeof LoginBusinessRoute
  QrTableRoute: typeof QrTableRoute
  AppIndexRoute: typeof AppIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AppTypeBusinessRoute: typeof AppTypeBusinessRouteWithChildren
  QrBusinessTableRoute: typeof QrBusinessTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/business': {
      id: '/login/business'
      path: '/login/business'
      fullPath: '/login/business'
      preLoaderRoute: typeof LoginBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$table': {
      id: '/qr/$table'
      path: '/qr/$table'
      fullPath: '/qr/$table'
      preLoaderRoute: typeof QrTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/$type/$business': {
      id: '/app/$type/$business'
      path: '/app/$type/$business'
      fullPath: '/app/$type/$business'
      preLoaderRoute: typeof AppTypeBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$business/$table': {
      id: '/qr/$business/$table'
      path: '/qr/$business/$table'
      fullPath: '/qr/$business/$table'
      preLoaderRoute: typeof QrBusinessTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$type/$business/appointments': {
      id: '/app/$type/$business/appointments'
      path: '/appointments'
      fullPath: '/app/$type/$business/appointments'
      preLoaderRoute: typeof AppTypeBusinessAppointmentsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/bookings': {
      id: '/app/$type/$business/bookings'
      path: '/bookings'
      fullPath: '/app/$type/$business/bookings'
      preLoaderRoute: typeof AppTypeBusinessBookingsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/calendar': {
      id: '/app/$type/$business/calendar'
      path: '/calendar'
      fullPath: '/app/$type/$business/calendar'
      preLoaderRoute: typeof AppTypeBusinessCalendarRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/coupons': {
      id: '/app/$type/$business/coupons'
      path: '/coupons'
      fullPath: '/app/$type/$business/coupons'
      preLoaderRoute: typeof AppTypeBusinessCouponsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/customer-recovery': {
      id: '/app/$type/$business/customer-recovery'
      path: '/customer-recovery'
      fullPath: '/app/$type/$business/customer-recovery'
      preLoaderRoute: typeof AppTypeBusinessCustomerRecoveryRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/dashboard': {
      id: '/app/$type/$business/dashboard'
      path: '/dashboard'
      fullPath: '/app/$type/$business/dashboard'
      preLoaderRoute: typeof AppTypeBusinessDashboardRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/festival-campaigns': {
      id: '/app/$type/$business/festival-campaigns'
      path: '/festival-campaigns'
      fullPath: '/app/$type/$business/festival-campaigns'
      preLoaderRoute: typeof AppTypeBusinessFestivalCampaignsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/loyalty': {
      id: '/app/$type/$business/loyalty'
      path: '/loyalty'
      fullPath: '/app/$type/$business/loyalty'
      preLoaderRoute: typeof AppTypeBusinessLoyaltyRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/marketing': {
      id: '/app/$type/$business/marketing'
      path: '/marketing'
      fullPath: '/app/$type/$business/marketing'
      preLoaderRoute: typeof AppTypeBusinessMarketingRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/menu': {
      id: '/app/$type/$business/menu'
      path: '/menu'
      fullPath: '/app/$type/$business/menu'
      preLoaderRoute: typeof AppTypeBusinessMenuRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/orders': {
      id: '/app/$type/$business/orders'
      path: '/orders'
      fullPath: '/app/$type/$business/orders'
      preLoaderRoute: typeof AppTypeBusinessOrdersRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/reports': {
      id: '/app/$type/$business/reports'
      path: '/reports'
      fullPath: '/app/$type/$business/reports'
      preLoaderRoute: typeof AppTypeBusinessReportsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/revenue': {
      id: '/app/$type/$business/revenue'
      path: '/revenue'
      fullPath: '/app/$type/$business/revenue'
      preLoaderRoute: typeof AppTypeBusinessRevenueRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/review-booster': {
      id: '/app/$type/$business/review-booster'
      path: '/review-booster'
      fullPath: '/app/$type/$business/review-booster'
      preLoaderRoute: typeof AppTypeBusinessReviewBoosterRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/services': {
      id: '/app/$type/$business/services'
      path: '/services'
      fullPath: '/app/$type/$business/services'
      preLoaderRoute: typeof AppTypeBusinessServicesRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/settings': {
      id: '/app/$type/$business/settings'
      path: '/settings'
      fullPath: '/app/$type/$business/settings'
      preLoaderRoute: typeof AppTypeBusinessSettingsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/subscription': {
      id: '/app/$type/$business/subscription'
      path: '/subscription'
      fullPath: '/app/$type/$business/subscription'
      preLoaderRoute: typeof AppTypeBusinessSubscriptionRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/tables': {
      id: '/app/$type/$business/tables'
      path: '/tables'
      fullPath: '/app/$type/$business/tables'
      preLoaderRoute: typeof AppTypeBusinessTablesRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/team': {
      id: '/app/$type/$business/team'
      path: '/team'
      fullPath: '/app/$type/$business/team'
      preLoaderRoute: typeof AppTypeBusinessTeamRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/templates': {
      id: '/app/$type/$business/templates'
      path: '/templates'
      fullPath: '/app/$type/$business/templates'
      preLoaderRoute: typeof AppTypeBusinessTemplatesRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/vip': {
      id: '/app/$type/$business/vip'
      path: '/vip'
      fullPath: '/app/$type/$business/vip'
      preLoaderRoute: typeof AppTypeBusinessVipRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/welcome': {
      id: '/app/$type/$business/welcome'
      path: '/welcome'
      fullPath: '/app/$type/$business/welcome'
      preLoaderRoute: typeof AppTypeBusinessWelcomeRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/whatsapp-campaigns': {
      id: '/app/$type/$business/whatsapp-campaigns'
      path: '/whatsapp-campaigns'
      fullPath: '/app/$type/$business/whatsapp-campaigns'
      preLoaderRoute: typeof AppTypeBusinessWhatsappCampaignsRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/whatsapp-history': {
      id: '/app/$type/$business/whatsapp-history'
      path: '/whatsapp-history'
      fullPath: '/app/$type/$business/whatsapp-history'
      preLoaderRoute: typeof AppTypeBusinessWhatsappHistoryRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/anniversary-campaigns/': {
      id: '/app/$type/$business/anniversary-campaigns/'
      path: '/anniversary-campaigns'
      fullPath: '/app/$type/$business/anniversary-campaigns/'
      preLoaderRoute: typeof AppTypeBusinessAnniversaryCampaignsIndexRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/anniversary-campaigns/month': {
      id: '/app/$type/$business/anniversary-campaigns/month'
      path: '/anniversary-campaigns/month'
      fullPath: '/app/$type/$business/anniversary-campaigns/month'
      preLoaderRoute: typeof AppTypeBusinessAnniversaryCampaignsMonthRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/anniversary-campaigns/today': {
      id: '/app/$type/$business/anniversary-campaigns/today'
      path: '/anniversary-campaigns/today'
      fullPath: '/app/$type/$business/anniversary-campaigns/today'
      preLoaderRoute: typeof AppTypeBusinessAnniversaryCampaignsTodayRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/anniversary-campaigns/tomorrow': {
      id: '/app/$type/$business/anniversary-campaigns/tomorrow'
      path: '/anniversary-campaigns/tomorrow'
      fullPath: '/app/$type/$business/anniversary-campaigns/tomorrow'
      preLoaderRoute: typeof AppTypeBusinessAnniversaryCampaignsTomorrowRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/anniversary-campaigns/week': {
      id: '/app/$type/$business/anniversary-campaigns/week'
      path: '/anniversary-campaigns/week'
      fullPath: '/app/$type/$business/anniversary-campaigns/week'
      preLoaderRoute: typeof AppTypeBusinessAnniversaryCampaignsWeekRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/birthday-campaigns/': {
      id: '/app/$type/$business/birthday-campaigns/'
      path: '/birthday-campaigns'
      fullPath: '/app/$type/$business/birthday-campaigns/'
      preLoaderRoute: typeof AppTypeBusinessBirthdayCampaignsIndexRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/birthday-campaigns/month': {
      id: '/app/$type/$business/birthday-campaigns/month'
      path: '/birthday-campaigns/month'
      fullPath: '/app/$type/$business/birthday-campaigns/month'
      preLoaderRoute: typeof AppTypeBusinessBirthdayCampaignsMonthRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/birthday-campaigns/today': {
      id: '/app/$type/$business/birthday-campaigns/today'
      path: '/birthday-campaigns/today'
      fullPath: '/app/$type/$business/birthday-campaigns/today'
      preLoaderRoute: typeof AppTypeBusinessBirthdayCampaignsTodayRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/birthday-campaigns/tomorrow': {
      id: '/app/$type/$business/birthday-campaigns/tomorrow'
      path: '/birthday-campaigns/tomorrow'
      fullPath: '/app/$type/$business/birthday-campaigns/tomorrow'
      preLoaderRoute: typeof AppTypeBusinessBirthdayCampaignsTomorrowRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/birthday-campaigns/week': {
      id: '/app/$type/$business/birthday-campaigns/week'
      path: '/birthday-campaigns/week'
      fullPath: '/app/$type/$business/birthday-campaigns/week'
      preLoaderRoute: typeof AppTypeBusinessBirthdayCampaignsWeekRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/customer-recovery/$days': {
      id: '/app/$type/$business/customer-recovery/$days'
      path: '/$days'
      fullPath: '/app/$type/$business/customer-recovery/$days'
      preLoaderRoute: typeof AppTypeBusinessCustomerRecoveryDaysRouteImport
      parentRoute: typeof AppTypeBusinessCustomerRecoveryRoute
    }
    '/app/$type/$business/customers/': {
      id: '/app/$type/$business/customers/'
      path: '/customers'
      fullPath: '/app/$type/$business/customers/'
      preLoaderRoute: typeof AppTypeBusinessCustomersIndexRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/customers/$id': {
      id: '/app/$type/$business/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/$type/$business/customers/$id'
      preLoaderRoute: typeof AppTypeBusinessCustomersIdRouteImport
      parentRoute: typeof AppTypeBusinessRoute
    }
    '/app/$type/$business/orders/$id': {
      id: '/app/$type/$business/orders/$id'
      path: '/$id'
      fullPath: '/app/$type/$business/orders/$id'
      preLoaderRoute: typeof AppTypeBusinessOrdersIdRouteImport
      parentRoute: typeof AppTypeBusinessOrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppTypeBusinessCustomerRecoveryRouteChildren {
  AppTypeBusinessCustomerRecoveryDaysRoute: typeof AppTypeBusinessCustomerRecoveryDaysRoute
}

const AppTypeBusinessCustomerRecoveryRouteChildren: AppTypeBusinessCustomerRecoveryRouteChildren =
  {
    AppTypeBusinessCustomerRecoveryDaysRoute:
      AppTypeBusinessCustomerRecoveryDaysRoute,
  }

const AppTypeBusinessCustomerRecoveryRouteWithChildren =
  AppTypeBusinessCustomerRecoveryRoute._addFileChildren(
    AppTypeBusinessCustomerRecoveryRouteChildren,
  )

interface AppTypeBusinessOrdersRouteChildren {
  AppTypeBusinessOrdersIdRoute: typeof AppTypeBusinessOrdersIdRoute
}

const AppTypeBusinessOrdersRouteChildren: AppTypeBusinessOrdersRouteChildren = {
  AppTypeBusinessOrdersIdRoute: AppTypeBusinessOrdersIdRoute,
}

const AppTypeBusinessOrdersRouteWithChildren =
  AppTypeBusinessOrdersRoute._addFileChildren(
    AppTypeBusinessOrdersRouteChildren,
  )

interface AppTypeBusinessRouteChildren {
  AppTypeBusinessAppointmentsRoute: typeof AppTypeBusinessAppointmentsRoute
  AppTypeBusinessBookingsRoute: typeof AppTypeBusinessBookingsRoute
  AppTypeBusinessCalendarRoute: typeof AppTypeBusinessCalendarRoute
  AppTypeBusinessCouponsRoute: typeof AppTypeBusinessCouponsRoute
  AppTypeBusinessCustomerRecoveryRoute: typeof AppTypeBusinessCustomerRecoveryRouteWithChildren
  AppTypeBusinessDashboardRoute: typeof AppTypeBusinessDashboardRoute
  AppTypeBusinessFestivalCampaignsRoute: typeof AppTypeBusinessFestivalCampaignsRoute
  AppTypeBusinessLoyaltyRoute: typeof AppTypeBusinessLoyaltyRoute
  AppTypeBusinessMarketingRoute: typeof AppTypeBusinessMarketingRoute
  AppTypeBusinessMenuRoute: typeof AppTypeBusinessMenuRoute
  AppTypeBusinessOrdersRoute: typeof AppTypeBusinessOrdersRouteWithChildren
  AppTypeBusinessReportsRoute: typeof AppTypeBusinessReportsRoute
  AppTypeBusinessRevenueRoute: typeof AppTypeBusinessRevenueRoute
  AppTypeBusinessReviewBoosterRoute: typeof AppTypeBusinessReviewBoosterRoute
  AppTypeBusinessServicesRoute: typeof AppTypeBusinessServicesRoute
  AppTypeBusinessSettingsRoute: typeof AppTypeBusinessSettingsRoute
  AppTypeBusinessSubscriptionRoute: typeof AppTypeBusinessSubscriptionRoute
  AppTypeBusinessTablesRoute: typeof AppTypeBusinessTablesRoute
  AppTypeBusinessTeamRoute: typeof AppTypeBusinessTeamRoute
  AppTypeBusinessTemplatesRoute: typeof AppTypeBusinessTemplatesRoute
  AppTypeBusinessVipRoute: typeof AppTypeBusinessVipRoute
  AppTypeBusinessWelcomeRoute: typeof AppTypeBusinessWelcomeRoute
  AppTypeBusinessWhatsappCampaignsRoute: typeof AppTypeBusinessWhatsappCampaignsRoute
  AppTypeBusinessWhatsappHistoryRoute: typeof AppTypeBusinessWhatsappHistoryRoute
  AppTypeBusinessAnniversaryCampaignsMonthRoute: typeof AppTypeBusinessAnniversaryCampaignsMonthRoute
  AppTypeBusinessAnniversaryCampaignsTodayRoute: typeof AppTypeBusinessAnniversaryCampaignsTodayRoute
  AppTypeBusinessAnniversaryCampaignsTomorrowRoute: typeof AppTypeBusinessAnniversaryCampaignsTomorrowRoute
  AppTypeBusinessAnniversaryCampaignsWeekRoute: typeof AppTypeBusinessAnniversaryCampaignsWeekRoute
  AppTypeBusinessBirthdayCampaignsMonthRoute: typeof AppTypeBusinessBirthdayCampaignsMonthRoute
  AppTypeBusinessBirthdayCampaignsTodayRoute: typeof AppTypeBusinessBirthdayCampaignsTodayRoute
  AppTypeBusinessBirthdayCampaignsTomorrowRoute: typeof AppTypeBusinessBirthdayCampaignsTomorrowRoute
  AppTypeBusinessBirthdayCampaignsWeekRoute: typeof AppTypeBusinessBirthdayCampaignsWeekRoute
  AppTypeBusinessCustomersIdRoute: typeof AppTypeBusinessCustomersIdRoute
  AppTypeBusinessAnniversaryCampaignsIndexRoute: typeof AppTypeBusinessAnniversaryCampaignsIndexRoute
  AppTypeBusinessBirthdayCampaignsIndexRoute: typeof AppTypeBusinessBirthdayCampaignsIndexRoute
  AppTypeBusinessCustomersIndexRoute: typeof AppTypeBusinessCustomersIndexRoute
}

const AppTypeBusinessRouteChildren: AppTypeBusinessRouteChildren = {
  AppTypeBusinessAppointmentsRoute: AppTypeBusinessAppointmentsRoute,
  AppTypeBusinessBookingsRoute: AppTypeBusinessBookingsRoute,
  AppTypeBusinessCalendarRoute: AppTypeBusinessCalendarRoute,
  AppTypeBusinessCouponsRoute: AppTypeBusinessCouponsRoute,
  AppTypeBusinessCustomerRecoveryRoute:
    AppTypeBusinessCustomerRecoveryRouteWithChildren,
  AppTypeBusinessDashboardRoute: AppTypeBusinessDashboardRoute,
  AppTypeBusinessFestivalCampaignsRoute: AppTypeBusinessFestivalCampaignsRoute,
  AppTypeBusinessLoyaltyRoute: AppTypeBusinessLoyaltyRoute,
  AppTypeBusinessMarketingRoute: AppTypeBusinessMarketingRoute,
  AppTypeBusinessMenuRoute: AppTypeBusinessMenuRoute,
  AppTypeBusinessOrdersRoute: AppTypeBusinessOrdersRouteWithChildren,
  AppTypeBusinessReportsRoute: AppTypeBusinessReportsRoute,
  AppTypeBusinessRevenueRoute: AppTypeBusinessRevenueRoute,
  AppTypeBusinessReviewBoosterRoute: AppTypeBusinessReviewBoosterRoute,
  AppTypeBusinessServicesRoute: AppTypeBusinessServicesRoute,
  AppTypeBusinessSettingsRoute: AppTypeBusinessSettingsRoute,
  AppTypeBusinessSubscriptionRoute: AppTypeBusinessSubscriptionRoute,
  AppTypeBusinessTablesRoute: AppTypeBusinessTablesRoute,
  AppTypeBusinessTeamRoute: AppTypeBusinessTeamRoute,
  AppTypeBusinessTemplatesRoute: AppTypeBusinessTemplatesRoute,
  AppTypeBusinessVipRoute: AppTypeBusinessVipRoute,
  AppTypeBusinessWelcomeRoute: AppTypeBusinessWelcomeRoute,
  AppTypeBusinessWhatsappCampaignsRoute: AppTypeBusinessWhatsappCampaignsRoute,
  AppTypeBusinessWhatsappHistoryRoute: AppTypeBusinessWhatsappHistoryRoute,
  AppTypeBusinessAnniversaryCampaignsMonthRoute:
    AppTypeBusinessAnniversaryCampaignsMonthRoute,
  AppTypeBusinessAnniversaryCampaignsTodayRoute:
    AppTypeBusinessAnniversaryCampaignsTodayRoute,
  AppTypeBusinessAnniversaryCampaignsTomorrowRoute:
    AppTypeBusinessAnniversaryCampaignsTomorrowRoute,
  AppTypeBusinessAnniversaryCampaignsWeekRoute:
    AppTypeBusinessAnniversaryCampaignsWeekRoute,
  AppTypeBusinessBirthdayCampaignsMonthRoute:
    AppTypeBusinessBirthdayCampaignsMonthRoute,
  AppTypeBusinessBirthdayCampaignsTodayRoute:
    AppTypeBusinessBirthdayCampaignsTodayRoute,
  AppTypeBusinessBirthdayCampaignsTomorrowRoute:
    AppTypeBusinessBirthdayCampaignsTomorrowRoute,
  AppTypeBusinessBirthdayCampaignsWeekRoute:
    AppTypeBusinessBirthdayCampaignsWeekRoute,
  AppTypeBusinessCustomersIdRoute: AppTypeBusinessCustomersIdRoute,
  AppTypeBusinessAnniversaryCampaignsIndexRoute:
    AppTypeBusinessAnniversaryCampaignsIndexRoute,
  AppTypeBusinessBirthdayCampaignsIndexRoute:
    AppTypeBusinessBirthdayCampaignsIndexRoute,
  AppTypeBusinessCustomersIndexRoute: AppTypeBusinessCustomersIndexRoute,
}

const AppTypeBusinessRouteWithChildren = AppTypeBusinessRoute._addFileChildren(
  AppTypeBusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  UseCasesRoute: UseCasesRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginBusinessRoute: LoginBusinessRoute,
  QrTableRoute: QrTableRoute,
  AppIndexRoute: AppIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  AppTypeBusinessRoute: AppTypeBusinessRouteWithChildren,
  QrBusinessTableRoute: QrBusinessTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
